# Generated by Django 5.0.3 on 2024-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
